

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: network-scanner-frontend
    ports:
      - "0.0.0.0:3000:80"  
    restart: unless-stopped
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
